# Maintenance of the handbook

## Availability

The Handbook's primary location is on the web (URL TBD). However, it is also a book, and we will, at regular intervals, make available printed copies and ebook versions. The online version and the ebook will be assigned Digital Object Identifiers (DOI). Online chapters will receive their own DOI for ease of citability. Both the ebook and the hard copy will be assigned ISBN numbers. The hard copy will be available for purchase through a number of outlets. The ebook will be available for download from the Handbook's primary location for free.

## Updating the Handbook

Invited or contributed additions will be incorporated into the Handbook by a J-PAL-based editorial team. Not all contributions can be accepted. Each contribution will be subject to editorial review, and may be sent out to referees. The entire process is mediated by a [Github workflow](https://guides.github.com/introduction/flow/), and while referee reports and editorial deliberations may not be public, the contents of the decision letter will be part of the public Github workflow.[^note1]. Contributions need to be licensed liberally, at least under [Creative Commons Attribution-NonCommercial (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/), and copyright will be retained by the contributing authors.

## Frequency of Updates

Updates will be accepted on a flow basis, and updates published on a flow basis as well (see [Versioning]). If there have been any updates, then a new version of the print copy will be issued once a year. 

## Versioning

We follow [Semantic Versioning](https://semver.org/) rules. The first official release is `V1.0`. Minor corrections (a "patch") will receive a third digit (e.g., `V1.0.1`), but which will not be identified on the title page. Contributions of new chapters, removal of chapters (obsolescence), or significant updates of existing chapters will trigger the increment of the minor version (`V1.1`, `V1.2`, ...). A new print version is associated with a major version update (`V2.0`).





[^note1]: For the technically inclined: it will be  the commit message of the pull request, or the rejection of such pull request.
