# Introduction
In order to provide guidance to current and future researchers, data providers, and administrators wishing to make data more broadly available, we would like to assemble a Handbook on making administrative data more broadly available for research and evidence-based policy.

The first part of the handbook provides an overview of existing solutions to common challenges encountered in the process of making administrative data accessible. This includes chapters by dedicated experts on specific ethical, legal, and technical challenges. 

There are already many excellent resources on administrative data access: the various challenges of making data available securely  (see e.g. @Reuter2010-xr, @Harron2017-qp,  @ADRF_Network2018-wl,  @Future_of_Privacy_Forum2017-kj ); resources on data held by national statistical offices (NSO) and the initial creation of integrated data systems, including (in the U.S.) work by [Actionable Intelligence for Social Policy (AISP)](https://www.aisp.upenn.edu/); the general "Five Safes" framework [@DesaiFiveSafesdesigning2016]; and guides for the European context, which include case studies ( @OECDEXPERTGROUPINTERNATIONAL2014 , @Bujnowska2019-eq). 
In this handbook, we hope to provide an accessible overview and concrete examples of applications of the different available solutions in real-world contexts.

For the second part of this handbook, we therefore collect a set of case studies that display the diverse experiences of those who have undertaken such endeavors. We would like to show how data access solutions were selected and how they worked in practice, guiding readers through the myriad of decisions for and against certain options; practices that have been found to be useful in a given context, but also choices that in retrospect might have been made differently. In addition, we would like to give an outlook on the possibilities for research and experiments using this data, and the many opportunities for improving policy once data is made accessible.

This handbook focuses broadly speaking on scenarios where confidential or proprietary data was made accessible to a broad group of researchers, be it by private, non-profit, or government organizations. This should include access by academic researchers who are not primarily associated with the institution that is creating, collecting, or making accessible the data in question. In most scenarios, there continue to be some access restrictions, i.e. the handbook does not primarily focus on situations where data have been successfully anonymized and posted for anybody to use, although some scenarios may have an "open data"  component. The handbook includes both scenarios where the data provider charges for access, whether for profit or for cost recovery, and where access is free. 

To facilitate use, case study contributions build on a common, comprehensive [template] of topics around administrative data access for research. On the one hand, the case studies discuss challenges that need to be considered, on the other they point to opportunities for innovative research and experiments, and highlight useful techniques in data quality, processing, or linking, including with simultaneously collected survey data. Each case study speaks to at least one of the topics identified in the template in detail. Not all topics are relevant in all contexts, and readers will see this reflected in the handbook contributions. As a whole, the collection of case studies aims to speak to the full range of  considerations, from the fundamental - why even think about making the data available? - to the most mundane (but often pressing) - how much does that computer infrastructure cost? 

Interested readers can use the [template] to self-evaluate, or use it as a planning tool for their own data access implementation. 
