# Acknowledgements {- #handbook_acknowledgements}

The editors of the Handbook would like to thank the Alfred P. Sloan Foundation for providing financial support that made this work possible. We would also like to express our thanks to all the authors who contributed to the Handbook and provided invaluable feedback and workshopping, as well as [Steven Glazerman](https://www.poverty-action.org/people/steven-glazerman), [Jennifer Sturdy](https://www.bitss.org/people/jennifer-sturdy/), and [Torsten Walter](https://nyuad.nyu.edu/en/academics/divisions/social-science/faculty/torsten-bernd-norbert-figueiredo-walter.html) for insightful comments and review.

We thank [Jim Shen](https://www.povertyactionlab.org/person/shen) for his work managing the Innovations in Data and Experiments for Action Initiative (IDEA) and the creation of the Handbook, while also coauthoring two chapters in this book, [Evan Williams](https://www.povertyactionlab.org/person/williams) for creating or co-creating many of the accompanying materials for the Handbook, such as the webinar series, and providing invaluable assistance from organizing the chapter review process to proof-reading, [Sam Friedlander](https://www.povertyactionlab.org/person/friedlander) for staffing IDEA early on, and the many J-PAL staff members who provided additional feedback on the various components of this Handbook.

[Elizabeth Bond](https://www.povertyactionlab.org/person/bond) designed the Handbook cover and other associated materials and Theresa Lewis provided copy editing for the Handbook. We appreciate their attention to detail and hard work that helped turn 16 distinct chapters into a cohesive whole. Additional thanks go to [Aparna Krishnan](https://www.povertyactionlab.org/person/krishnan) (Project Director, J-PAL South Asia) and [Claudia Macías](https://www.povertyactionlab.org/person/macias) (Associate Director of Policy, Training and Research, J-PAL Latin America & the Caribbean) for their continuing support of IDEA.
