```{r, echo=FALSE}
source("programs/_plot_physical.R")
library(kableExtra)
```


## Custom Testing

This is a test page for custom formatting.

### Breakout Block Test

Testing breakout boxes.

```{block2, type='bbox'}
**Bold Text Title**

Content in a breakout box. Words and stuff

can I put a plot here? (no)
  
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
  
Can I put in a picture (no)

```

### Tables


```{r, echo=FALSE, message=FALSE, warnings=FALSE}

text_tbl <- data.frame(
  Items = c("Population/Sample Size", 
            "Time Period covered and frequency",
            "Additional information",
            "Population/Sample Size", 
            "Time Period covered and frequency",
            "Additional information","Population/Sample Size", 
            "Time Period covered and frequency",
            "Additional information"),
  Features = c(
    "2% random sample (more than 1.8 million individuals) of the Integrated Employment Biographies, a database which includes records from<br><br>
    - 1975 onwards: employment subject, receipt of benefits in accordance with Social Code Act III<br>
    - 1999 onwards: Marginal part-time employment<br>
    - 2000 onwards: participation in an employment or training measure<br>
    - 2007 onwards: Registered jobseeker",
    "1975 until 2017 for West Germany, 1992 until 2017 for East Germany, updated every 2nd year by RDC-IAB", 
    "Administrative Data<br>
    DOI: 10.5164/IAB.SIAB7517.de.en.v1",
    "Repeated cross sectional dataset (640,000–1.5 million establishments) on June 30, on all establishments with at     least one employee liable to social security (until 1988) and/or at least one marginal worker (since 1999), and      thereof a 50% random sample",
    "1975 until 2018 for West Germany, 1992 until 2018 for East Germany, annual updated by RDC-IAB",
    "Administrative Data<br>
    DOI: 10.5164/IAB.BHP7518.de.en.v1",
    "Worker information from administrative data are linked to the IAB-Establishment Panel, an annual representative     survey since 1993 in West Germany and 1996 in East Germany including approx. 16,000 establishments per year
    Stratified sample of all establishments with at least one employee liable to social security on June 30 of the       year before by establishment size, industry, and federal state.<br><br>
    Two versions of LIAB:<br>
    - LIAB cross-sectional model: all establishment surveys combined with administrative worker data as of June 30       (establishment: 67,407 in total; individuals approx. 12.5 million in total)<br>
    - LIAB longitudinal model: selection of repeatedly interviewed establishments (2009-2016) combined with              longitudinal worker biographies (establishment: 41,777 in total; individuals approx. 1.7 million in total)",
    "LIAB Cross-sectional model: 1993–2017<br>
    LIAB longitudinal model: 1975–2017",
    "Administrative data linked with survey data<br>
    DOI: 10.5164/IAB.LIABQM29317.de.en.v1<br>
    DOI: 10.5164/IAB.LIABLM7517.de.en.v1"
  )
)

kable(text_tbl, escape = F, caption="Selected ||RDC-IAB|| data (version1)", col.names = NULL, booktabs=T) %>%
  kable_styling() %>%
  column_spec(1, border_right = T) %>%
  column_spec(2, width = "30em") %>%
  pack_rows("Sample of Integrated Labour Market Biographies (||SIAB||)",1,3) %>%
  pack_rows("||Establishment History Panel|| (||BHP||)",4,6) %>%
  pack_rows("||Linked Employer-Employee Data|| (||LIAB||)",7,9) %>%
  footnote(general="The time period covered by each data set represents the status as of 02 June 2020. For a complete list of all data products see the [IAB website](https://fdz.iab.de/en/FDZ_Overview_of_Data.aspx).")
  
```