## Appendix B

**Sample ||Data Sponsor|| Agreement**

Private Equity Sponsor DATA Agreement

This Private Equity Sponsor Data Agreement (the "**Agreement**") is made [\_\_\_\_\_\_\_\_\_], [\_\_\_\_\_\_\_\_\_] (the "**Effective** **Date**"), by and between Private Capital Research Institute, Inc. ("**PCRI**"), a Delaware not-for-profit corporation, having its principal place of business at 278 Cutler Road, South Hamilton, MA 01982, and [\_\_\_\_\_\_\_\_\_], a [\_\_\_\_\_\_\_\_\_] corporation ("**Private Equity Sponsor**") having its principal place of business at [\_\_\_\_\_\_\_\_\_\_\_\_\_] (each of PCRI and Private Equity Sponsor, a "**Party**" and, together, the "**Parties**").

**WHEREAS**, PCRI is organized exclusively for charitable purposes within the meaning of section 501(c)(3) of the Internal Revenue Code of 1986, including for the purpose of sponsoring research projects on private capital and disseminating the results of such research (the "**PCRI Purposes**");

**WHEREAS**, in pursuit of the PCRI Purposes, PCRI (a) is developing and intends to maintain two (2) databases of private equity activity worldwide, which will include fund-level data and deal-level data, respectively, that PCRI (i) obtains from third-party providers; (ii) is provided by managers of certain private equity funds, including Private Equity Sponsor, and by Private Equity Sponsor's subsidiaries or affiliates or related companies, the investment funds that are indirectly managed by Private Equity Sponsor, the existing or potential investors in such funds or the companies in which such funds have invested or are considering or have considered investing, or any of the directors, partners, officers, employees, agents, advisors and representatives of any of the foregoing (each a "**Private Equity Sponsor Party**" and, collectively, the "**Private Equity Sponsor Parties**"; and (iii) collects through its own research and the efforts of its contractors, students and other persons, including from publicly available documents (the "**Consolidated Databases**") and (b) will provide access to the Consolidated Databases solely to academic, non-commercial researchers on the terms described in this Agreement for purposes of their carrying out and publishing research based thereon ((a) and (b), together, the "**Project**"); and

**WHEREAS**, Private Equity Sponsor possesses data and databases of its and its funds private equity activity that it is willing to provide to PCRI on the basis of the terms and conditions set out in this Agreement for inclusion in the Consolidated Databases and otherwise to facilitate the Project (when and as provided to PCRI, the "**Sponsor Data**");

**NOW, THEREFORE**, in consideration of the foregoing and the covenants and agreements set forth herein, the Parties hereby agree as follows:

1. **[LICENSE; ACCESS TO SPONSOR DATA; OWNERSHIP OF DATA]{.ul}**

1.1 [**License**.]{.ul} Subject to the terms of this Agreement, Private Equity Sponsor hereby grants to PCRI and PCRI hereby accepts from Private Equity Sponsor a royalty-free, non-exclusive, non-transferable and non-sublicensable (except as permitted by this Agreement), worldwide right and license during the Term (as defined below) to receive, reproduce, store, combine (as described in Section 2), make derivative works of, distribute and otherwise make available, and use the Sponsor Data solely for and in connection with the Project (the "License"). PCRI has the right to sublicense the foregoing rights to receive, reproduce and store Sponsor Data to its data hosting provider for purposes of hosting the Sponsor Data and the Consolidated Databases in connection with the Project.

1.2 [Access to Sponsor Data]{.ul}

a. After the Effective Date, on a date to be agreed by the Parties, Private Equity Sponsor will provide all Sponsor Data from the date of Private Equity Sponsor's inception or from another start date as mutually agreed on (the "Initial Download") and, on a basis and frequency to be agreed by the Parties, will thereafter provide updates to such Sponsor Data.  
b. Private Equity Sponsor shall provide PCRI with the Sponsor Data by such methods and media as the Parties may agree. If Private Equity Sponsor engages a third party to collect, store or maintain any Sponsor Data, Private Equity Sponsor hereby authorizes PCRI to obtain from such third party any such Sponsor Data that PCRI is permitted to receive under this Agreement. Private Equity Sponsor and PCRI shall each notify such third party of Private Equity Sponsor's foregoing authorization promptly after the execution of this Agreement or the date on which Private Equity Sponsor engages such third party for such purposes.  
c. Private Equity Sponsor shall assist PCRI, upon PCRI's reasonable request and at times mutually agreed on by the Parties, in understanding the Sponsor Data.  
d. Nothing herein shall prevent Private Equity Sponsor from withholding certain information of Private Equity Sponsor as it may determine from time to time.

1.3 [**Ownership of Data**.]{.ul} At all times, subject to the License, Private Equity Sponsor will own and retain all right, title, and interest in and to the Sponsor Data. At all times, subject to the License and to its other licenses and agreements with other providers of data, including other private equity sponsors, and persons, PCRI will own and retain all right, title, and interest in and to the Consolidated Databases.

2. **[USE OF SPONSOR DATA]{.ul}**

2.1 [Consolidated Databases]{.ul}

a. The License authorizes PCRI, at its discretion, to combine some or all of the Sponsor Data with data from other sources into the Consolidated Databases. Except for the purpose of remedying any breaches by PCRI of its obligations under this Agreement, Private Equity Sponsor acknowledges that it has and will have no ability to monitor PCRI's use of the Sponsor Data.  
b. PCRI may have access to the Consolidated Databases for purposes of maintaining, preserving, archiving, operating, and updating. In addition, PCRI may access the Consolidated Databases for purposes of preparing white papers and other documentation about the Consolidated Databases both for internal purposes and to share such materials with sponsors and other supporters of PCRI, including, as appropriate, Private Equity Sponsor. Except as provided in Section 2.1(a), Private Equity Sponsor acknowledges that it will have no rights in, and no ability or right to access, the Consolidated Databases for any purpose.

2.2 [Research Uses]{.ul}

a. Except as provided in Section 2.1(b), only academic researchers conducting academic research pursuant to research proposals approved in accordance with this Section 2.2 will have access to the Consolidated Databases (each, an "Approved Researcher"). In no event shall an Approved Researcher have access to any Sponsor Data that identifies Private Equity Sponsor as the source of such data.  
b. PCRI has established or will establish a research advisory committee consisting of the PCRI director, PCRI research director, and such other academics as may be appointed by PCRI to serve on the committee from time-to-time (the "**Research Advisory Committee**"). One of the principal purposes of the Research Advisory Committee is to receive, review and approve proposals from academic researchers to conduct research on the Consolidated Databases.  
c. The Research Advisory Committee will entertain and review proposals only from persons associated with (i) accredited colleges and universities who are conducting academic research (and not for commercial purposes or entities), (ii) other types of not-for-profit organizations that are organized for or conduct research, or (iii) research groups of government organizations; *provided*, *however*, that the Research Advisory Committee will only review proposals if and to the extent they propose projects for which the research results are not specifically intended to benefit commercial organizations and for which the proposing person will not use such results for commercial purposes.  
d. If the Research Advisory Committee approves a proposal that is consistent with the requirements of Section 2.2(c) and any other eligibility criteria as it may establish (each an "Approved Proposal"), then the Approved Researcher who submitted the proposal will be required to enter into an agreement with PCRI (the "Data Access Agreement") before being provided access to the Consolidated Databases. The Data Access Agreement will, among other things: 1) require that the Approved Researcher may have access to and use the Consolidated Databases solely for and in connection with carrying out the research project set forth in the Approved Proposal; 2) without limiting the foregoing, prohibit the Approved Researcher from using the Consolidated Databases for any activities other than those set forth in the Approved Proposal (including, without limitation, for commercial or for-profit consulting or other activities of the Approved Researcher or other researchers or institutions with which he or she is affiliated); 3) authorize the Approved Researcher only to download regression and cross-tabulations based on the aggregate data in the Consolidated Databases and not Sponsor Data specific to Private Equity Sponsor; 4) prohibit the Approved Researcher from attempting to identify providers of individual items of data, including with respect to the Sponsor Data; 5) prohibit the Approved Researcher from downloading material parts of the Consolidated Databases or any Sponsor Data therein; 6) require the Approved Researcher to adhere to security and confidentiality obligations that are at least as stringent as those obligations set forth in Section 3 herein and expressly provide that the Private Equity Sponsor is an intended third party beneficiary of such obligations; 7) require that the Approved Researcher, upon completion of the research, certify that the Consolidated Databases have only been and will only be used for carrying out the research project set forth in the Approved Proposal; 8) provide that the Approved Researcher owns all rights in any reports or data resulting from the research project set forth in the Approved Proposal, subject to the rights of other persons in the underlying data; 9) disclaim any warranties with respect to the Consolidated Databases and all data therein; and 10) provide that the Approved Researcher will not assert any claims against a Private Equity Sponsor Party with respect to the Consolidated Databases or any Sponsor Data.

3. [CONFIDENTIALITY; **SECURITIES;** SECURITY]{.ul}

3.1 [Confidentiality Obligations.]{.ul}

a. Each Party that receives Confidential Information (the "**Receiving Party**") of the other Party (the "**Disclosing Party**") agrees to hold such Confidential Information in strict confidence and to not disclose any part of it, other than to its directors, officers, employees, agents, consultants or other representatives (collectively, "**Representatives**") and third parties specifically permitted by this Agreement who have a need to know such Confidential Information for purposes of the Agreement and who is subject to the obligations imposed on the Receiving Party under this Section 3.1. The Receiving Party will ensure that any Representative or any such third party complies with such obligations and agrees to be responsible for any such person's breach thereof. The Receiving Party agrees that it will take all reasonable steps to protect the Confidential Information from unauthorized or inadvertent disclosure or use and will take such steps that it takes to protect its own confidential information. Unless otherwise agreed in writing by the Parties, (i) PCRI will not identify any of the Private Equity Sponsor Parties by name or distinguishing characteristic, or provide information that would allow a reasonable person to deduce or infer its identity, in connection with any Confidential Information provided by any Private Equity Sponsor Party to PCRI and (ii) will not use the Confidential Information provided by any Private Equity Sponsor Party other than for purposes of the Project. "**Confidential Information**" means information of the Disclosing Party that the Receiving Party knows or, given the circumstances of disclosure, should know, or has been advised by the Disclosing Party, is not generally known to the public or the trade, or which is specifically designated by the Disclosing Party as "confidential" at the time of disclosure and, without limiting the foregoing, includes any non-public information about a Private Equity Sponsor Party and the Sponsor Data. The Receiving Party shall provide the Disclosing Party with prompt notice if the Receiving Party (A) becomes legally compelled to disclose any of the Confidential Information, so that the Disclosing Party may seek a protective order or other appropriate remedy or (B) becomes aware of any loss or unauthorized disclosure of Confidential Information, in which event the Receiving Party will take all reasonable actions, and cooperate in any reasonable actions taken by the Disclosing Party, to prevent, remedy or minimize such loss or unauthorized disclosure of Confidential Information.  
b. The obligations of confidentiality set forth in Section 3.1(a) do not apply to information which the Receiving Party demonstrates (i) is, at the time of the disclosure, or subsequently through no act or omission of the Receiving Party, becomes generally available to the public; (ii) was or is rightfully known to the Receiving Party through a third party with no obligation of confidentiality; or (iii) was independently developed or discovered by the Receiving Party without any reference to the Confidential Information.

3.2 [Securities.]{.ul} PCRI understands and acknowledges that United States securities laws restrict both the purchase and sale of securities by persons who possess material non-public information relating to the issuer of such securities and the communication of such information to any other person under circumstances in which it is reasonably foreseeable that such other person is likely to purchase or sell such securities.

3.3 [Security.]{.ul} PCRI shall maintain the Sponsor Data on servers and other media that are subject to physical, logistical and other security measures agreed between the Parties, which measures shall include, at a minimum, maintaining the Sponsor Data when it resides on a server behind a firewall, and shall take reasonable steps to monitor each Approved Researcher's use of the Sponsor Data. PCRI shall promptly notify Private Equity Sponsor of any breach of its security measures that implicate the Sponsor Data and promptly take all reasonable actions to remedy such breaches.

4. **[TRADEMARK LICENSE; RELATIONSHIP OF THE PARTIES]{.ul}**

4.1 [Trademark License.]{.ul} Private Equity Sponsor grants PCRI a limited, royalty-free, worldwide, non-exclusive, non-sublicenseable and non-transferable (except as permitted by this Agreement) right during the Term to use the trademarks and trade names (the "**Marks**") of Private Equity Sponsor solely for the purpose of indicating that Private Equity Sponsor is a provider of data to PCRI and subject to the prior approval of the Private Equity Sponsor, *provided*, *however*, that such prior approval is not required for any use that is the same as or is substantially similar to a previously approved use. Except as authorized pursuant to this Section 4.1, neither Party has any rights to utilize any of the other Party's Marks, or any Mark confusingly similar thereto, for any purpose other than as expressly authorized in writing by such Party.

4.2 [Relationship.]{.ul} Private Equity Sponsor is considered an independent contractor to PCRI. Nothing in the Agreement shall be construed or applied to create or imply the relationship of partners, agency, joint venturers, or of any employee or employer between the Parties. Neither Party has the power to bind the other Party or incur obligations on the other Party's behalf without the other Party's prior approval, and neither Party may represent that it has such right.

5. **[REPRESENTATIONS AND WARRANTIES]{.ul}**

5.1 [Representations and Warranties.]{.ul} Each Party represents and warrants that it has duly authorized, executed and delivered this Agreement, which, subject to the due execution and delivery hereof by the other Party, constitutes the legal, valid and binding obligation of such Party enforceable against such Party in accordance with its terms. Each Party represents and warrants that it has the right and ability to perform the obligations and covenants provided for in this Agreement.

5.2 [Disclaimer of Liability.]{.ul} PCRI understands and acknowledges that no Private Equity Sponsor Party is making, and each expressly disclaims, any representation or warranty, express or implied, as to the accuracy or completeness of any Confidential Information or any Sponsor Data.

6. **[LIMITATION OF LIABILITY]{.ul}**

6.1 [Damages Exclusion.]{.ul} UNDER NO CIRCUMSTANCES WILL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT, OR TO ANY LOSS OF DATA OR LOSS OF PROFITS, REGARDLESS OF WHETHER OR NOT SUCH DAMAGE COULD HAVE BEEN FORESEEN OR PREVENTED.

6.2 [Cap on Liability.]{.ul} THE LIABILITY OF EACH PARTY TO THE OTHER PARTY FOR ALL CLAIMS ARISING UNDER OR RELATED TO THIS AGREEMENT SHALL BE LIMITED TO ONE THOUSAND U.S. DOLLARS (\$1,000); PROVIDED, HOWEVER, THAT THE FOREGOING LIMITATION SHALL NOT APPLY TO THE EXTENT THAT SUCH LIABILITY RESULTED FROM SUCH PARTY'S INTENTIONAL MISCONDUCT, STRICT LIABILITY, FRAUD OR MISREPRESENTATION.

6.3 [Specific Performance.]{.ul} NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS SECTION 6, PCRI ACKNOWLEDGES THAT, DUE TO THE UNIQUE AND PROPRIETARY NATURE OF THE CONFIDENTIAL INFORMATION, MONEY DAMAGES WOULD NOT BE A SUFFICIENT REMEDY FOR ANY BREACH OF THIS AGREEMENT BY PCRI OR ITS REPRESENTATIVES AND PRIVATE EQUITY SPONSOR SHALL BE ENTITLED TO SEEK SPECIFIC PERFORMANCE AND TO INJUNCTIVE OR OTHER EQUITABLE RELIEF IN ADDITION TO ALL OTHER REMEDIES AVAILABLE TO ANY PRIVATE EQUITY SPONSOR AT LAW OR AT EQUITY AS A REMEDY FOR ANY SUCH BREACH. IN THE EVENT OF LITIGATION RELATING TO THIS AGREEMENT AND UPON FINAL DETERMINATION PURSUANT TO SECTION 9.7 BY AN ARBITRATOR WITH RESPECT THERETO, THE NON-PREVAILING PARTY IN SUCH LITIGATION SHALL REIMBURSE THE PREVAILING PARTY FOR ITS REASONABLE COSTS AND EXPENSES INCURRED IN CONNECTION WITH SUCH LITIGATION.

6.4 [Claims by PCRI.]{.ul} PCRI AGREES NOT TO BRING ANY CLAIMS AGAINST PRIVATE EQUITY SPONSOR RELATING TO ANY CONFIDENTIAL INFORMATION OR SPONSOR DATA THAT PCRI RECEIVES FROM THE PRIVATE EQUITY SPONSOR.

7. **[TERM AND TERMINATION]{.ul}**

7.1 [Term.]{.ul} The term of this Agreement commences on the Effective Date and will remain in force unless terminated as set forth in this Section 7 (the "**Term**").

7.2 [Termination.]{.ul}

a. The Parties may terminate this Agreement by mutual agreement.  
b. Either Party may terminate this Agreement with thirty (30) days' prior written notice to the other Party.  
c. In the event that one Party materially breaches this Agreement, upon notice of the other Party, the breaching Party shall have the right to remedy such the breach within thirty (30) days of receipt of such notice. If the breaching Party fails to remedy such breach within such thirty (30)-day period, the non-breaching Party may (at its option) terminate this Agreement upon written notice to the breaching Party.  
7.3 [Effect of Termination.]{.ul} Upon termination of this Agreement by Private Equity Sponsor pursuant to Section 7.2(c), the License shall terminate and, within a reasonable timeframe, PCRI shall purge all Sponsor Data from the Consolidated Databases; provided, however, that nothing herein shall limit the rights of any Approved Researcher to use, solely in conformity with the Data Access Agreement, any Sponsor Data that such Approved Researcher had used prior to, or possesses as of, the date of such termination.

7.4 [Survival.]{.ul} Sections 1.1, 1.3, 2, 3, 5, 6, 4.1, 7.2(c), 7.3, 8, and 9 and this Section 7.4 shall survive the termination of this Agreement.

8. **[INDEMNIFICATION]{.ul}**

8.1 [PCRI Indemnity.]{.ul} PCRI shall indemnify, defend and hold harmless each Private Equity Sponsor Party, and its officers, directors, employees, members, agents, representatives, and contractors, and each of their successors and permitted assignees (collectively, the "**Private Equity Sponsor Party Indemnitees**"), for any claims, actions, demands, costs, damages, liabilities, and expenses (including, without limitation, costs of litigation and reasonable attorneys' fees) against or incurred by any Private Equity Sponsor Party Indemnitee arising out of a breach of this Agreement by PCRI or brought against any Private Equity Sponsor Party Indemnitee by any Approved Researcher.

8.2 [Procedure.]{.ul} PCRI's obligation to indemnify the Private Equity Sponsor Party Indemnitees is conditioned on Private Equity Sponsor giving PCRI prompt written notice of any claim or litigation to which PCRI's indemnification obligation applies and full control of the defense and disposition (by compromise, settlement, or other resolution but excluding any admission of wrongdoing or incurring of liability or obligation by the Private Equity Sponsor Party Indemnitee) of such claim or litigation; provided, however, that PCRI shall not settle a claim or litigation requiring payment by or imposing any obligations on any of the Private Equity Sponsor Party Indemnitees without its or their prior written consent.

9. **[MISCELLANEOUS]{.ul}**

9.1 [Notices.]{.ul} All notices under the Agreement must be in writing and may be sent by one Party to the other Party by registered U.S. postal mail, reputable courier services (such as Federal Express) or facsimile (with confirmation from the other Party), or delivered in person, or (except for notices of breach of this Agreement) sent by e-mail with confirmation from the other Party (except for notices of breach of the Agreement) at the mailing address, facsimile number or email address set out below, or to such other address, number or persons as the Parties may from time to time designate in writing in the manner provided in this Section 9.1. Any notice served personally shall be considered given at the time of service. Any notice sent by registered mail shall be deemed to have been received five (5) business days after posting. Any other notice shall be deemed to have been received on the date of confirmed delivery (if given by courier) or on the date of confirmed transmission (if given by facsimile or e-mail).

If to Private Equity Sponsor:  
[ ]  
Facsimile: [ ]  
E-mail: [ ]  

If to PCRI:  
Josh Lerner  
278 Cutler Road  
South Hamilton, MA 01982  
Facsimile: (617) 495-3817  
E-mail: josh@hbs.edu

9.2 [Amendment.]{.ul} Except as otherwise permitted herein, this Agreement may be amended or varied only by a written amendment signed by both Parties.

9.3 [Waiver.]{.ul} If either Party delays or fails to exercise any right or remedy under this Agreement, that Party will not have waived that right or remedy or any other right or remedy on any other occasion.

9.4 [Assignment.]{.ul}

a. This Agreement may be assigned by Private Equity Sponsor to a third party, *provided* that Private Equity Sponsor gives PCRI notice of the assignment.  
b. This Agreement may not be assigned by PCRI without the prior written consent of Private Equity Sponsor. Notwithstanding the foregoing, if PCRI ceases operation and transfers responsibility for the Project to another not-for-profit entity, PCRI may assign this Agreement, and any of its rights or obligations, including the License, to such not-for-profit entity, *provided* that such entity agrees in writing to be bound to the terms of this Agreement and, *provided*, *further*, that PCRI gives Private Equity Sponsor notice of any such assignment and a copy of the assignee's agreement to be bound by the terms of this Agreement.  
c. This Agreement shall be binding upon and inure to the benefit of the Parties and their respective successors and permitted assigns.

9.5 [No Exclusivity.]{.ul} The rights and obligations of this Agreement are non-exclusive. Nothing herein prevents either Party from entering into similar agreements with other entities.

9.6 [Governing Law.]{.ul} This Agreement will be governed in all respects by and construed in accordance with the laws of the Commonwealth of Massachusetts, without giving effect to its principles or rules of conflict of laws to the extent such principles or rules are not mandatorily applicable by statute and would require or permit the application of the laws of another jurisdiction.

9.7 [Dispute Resolution.]{.ul} Any dispute, claim or controversy arising out of or relating to this Agreement or the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by arbitration in Boston, Massachusetts before one (1) arbitrator. The arbitration shall be administered by JAMS pursuant to its Comprehensive Arbitration Rules and Procedures (the "**Rules**") and in accordance with the Expedited Procedures in those Rules. Judgment on any award may be entered in any court having jurisdiction. This Section 9.7 shall not preclude the Parties from seeking provisional remedies in aid of arbitration from a court of appropriate jurisdiction, including, but not limited to, the remedies available pursuant to Section 6.3.

9.8 [Severability.]{.ul} If any provision of this Agreement (or any portion thereof) or the application of any such provision (or any portion thereof) to any person shall be held invalid, illegal or unenforceable in any respect by a court of competent jurisdiction, such invalidity, illegality or unenforceability shall not affect any other provision hereof (or the remaining portion thereof) or the application of such provision to any other persons, which shall remain in full force and effect, and the Parties shall endeavor to fulfill the intent of the severed provision to the extent permitted by law.

9.9 [Benefit.]{.ul} This Agreement is for the sole benefit of the Parties and nothing herein expressed or implied shall give or be construed to give to any person, other than the Parties, any legal or equitable rights hereunder; provided, however, that each Private Equity Sponsor Party Indemnitee is an intended third-party beneficiary of Section 8.1 and permitted to enforce such Section in accordance with its terms.

9.10 [Interpretation and Construction.]{.ul} The section and subsection headings of this Agreement are solely for the purpose of reference, are not part of the agreement of the Parties and shall not in any way affect the meaning or interpretation of this Agreement. As used in this Agreement, all references to days will be deemed references to calendar days unless expressly stated otherwise. Unless the context otherwise requires, as used in this Agreement, all terms used in the singular will be deemed to refer to the plural as well, and vice versa. The words "hereof" and "herein" and words of similar import referring to this Agreement refer to this Agreement as a whole and not to any particular provision of this Agreement. No interpretation of this Agreement will be made in favor of either Party by reason of this Agreement having been prepared by one or the other of the Parties.

9.11 [Entire Agreement.]{.ul} This Agreement contains the Parties' entire understanding regarding its subject matter and supersedes all agreements, proposals, and other representations, statements, negotiations, and undertakings in each case, verbal or written, relating to such subject matter.

9.12 [Counterparts.]{.ul} This Agreement may be executed in one or more counterparts, each of which, when sent or delivered in accordance with Section 9.1, will be deemed to be an original copy of this Agreement and all of which, when taken together, will be deemed to constitute one and the same Agreement. Signatures on copies sent by facsimile or on PDF copies attached to emails will serve as originals for purposes of executing this Agreement.

IN WITNESS WHEREOF, each of the Parties has caused this Agreement to be executed by its duly authorized officer, as of the date written below.

**[Private Equity Sponsor]**

By:  
Name:  
Title:  
Fax:  

**Private Capital Research Institute, Inc.**

By:  
Name:  
Title:  
Fax:  
