### Appendix B

  ------------------------------------------------ -------------------------------------------------------------
  [Fill in Title of Research Study here]           [Fill in Stanford Principal Investigator name here]
  ------------------------------------------------ -------------------------------------------------------------

**DATA USE AGREEMENT BETWEEN SAN FRANCISCO UNIFIED SCHOOL DISTRICT ANDSTANFORD RESEARCH ORGANIZATION**

This Data Use Agreement ("Agreement") is entered into by and between San Francisco Unified School District (hereinafter referred to as "SFUSD" or "District") and The Board of Trustees of the Leland Stanford Junior University ("Stanford University") on behalf of its Principal Investigator, *[Fill in Researcher name here]*, "Stanford Research Organization/Stanford Researcher," and is dated for convenience *[date]*.

WHEREAS, SFUSD and Stanford University have entered into an agreement whereby SFUSD has transferred data and information to Stanford University's Center for Education Policy Analysis so that Stanford University may store and release SFUSD's data and information for research studies approved by SFUSD ("SFUSD Approved Studies");

WHEREAS, this Agreement sets forth and describes the research project proposed by Stanford Research Organization/Stanford Researcher, and the means to be used by Stanford Research Organization/Stanford Researcher to ensure the confidentiality and security of information and data to be stored, accessed and used by the Stanford Research Organization/Stanford Researcher.

**A. THE FAMILY EDUCATIONAL RIGHTS AND PRIVACY ACT**

The Family Educational Rights Privacy Act ("FERPA") permits the release of personally identifiable student data without prior written parental consent if the release is to "organizations conducting studies for, or on behalf of, educational agencies or institutions for the purpose of developing, validating, or administering predictive tests, administering student aid programs, and improving instruction, if such studies are conducted in such a manner as will not permit the personal identification of students and their parents by persons other than representatives of such organizations and such information will be destroyed when no longer needed for the purpose for which it is conducted." 20 USC 1232g(b)(1)(F). Each party agrees to comply with FERPA in its performance of this Agreement.

**B. PURPOSE**

*[Summarize the purpose of the research. The form will expand as you type]*

To accomplish the purpose described above, Stanford Research Organization/Stanford Researcher will seek to answer the following research questions:

*Research Questions*

**C. SCOPE**

*[Describe the scope of the research. Who is being studied, which school(s), grades, what year(s), what topics, what type of access (data or surveys or interviews) etc.]*

**D. NATURE OF DATA**

To address these questions, Stanford Research Organization/Stanford Researcher requests the specific SFUSD records or data listed in Attachment A ("Specific Records and Data Elements") which shall be incorporated into this Agreement by reference as though fully set forth herein.

**E. IRB APPROVAL FROM STANFORD UNIVERSITY**

As part of the approval process with the District, Stanford Research Organization/Stanford Researcher must also receive approval as necessary from Stanford University Institutional Review Board (IRB).

**F. TRANSFER OF DATA**

Stanford Research Organization/Stanford Researcher shall use a secure, mutually agreed upon means and schedule for protection of the Data from unauthorized access or use. The Parties agree that the data may be electronically transferred via the Stanford-SFUSD Google Suite shared drive accessible to authorized users via secure log-in only.

Stanford Research Organization/Stanford Researcher shall specify in Attachment A the method of secure transmission of the Data and the location/address where the Data is to be transferred.

**G. PERIOD OF AGREEMENT**

This Agreement shall be effective when fully signed by both parties, and will terminate on *Month, Day, Year* unless terminated earlier by either party pursuant to Section J. ("Termination"). Notwithstanding the foregoing, the parties understand that this Agreement falls under a master Data Exchange and Warehousing Agreement ("Warehousing Agreement") between SFUSD and Stanford University, and that if at any time the Warehousing Agreement expires or is terminated, then this Agreement will also expire or be terminated at that time.

**H. STANFORD RESEARCH ORGANIZATION RESPONSIBILITIES**

Stanford Research Organization/Stanford Researcher agrees to the following confidentiality statements:

1. Stanford Research Organization/Stanford Researcher acknowledges that these data are confidential data and proprietary to SFUSD, and agree to use appropriate and reasonable measures to protect such information from unauthorized disclosures and to comply with all applicable laws and regulations including but not limited to the California Education Code and the Family Education Rights and Privacy Act (FERPA).

2. Stanford Research Organization/Stanford Researcher shall designate *[Name]*, *[title]* as the person responsible for the security and confidentiality of the data and will notify SFUSD immediately in writing of any change in designee.

3. Stanford Research Organization/Stanford Researcher will use appropriate safeguards to prevent the use or disclosure of the information other than as provided by this data use Agreement.

4. Stanford Research Organization/Stanford Researcher shall instruct all staff with access to data provided by District to Stanford University pursuant to this Agreement in the requirements for handling confidential student information, and require each person who will have access to such information to acknowledge the confidentiality obligations of the Data under this Agreement. Stanford Research Organization/Stanford Researcher shall list all staff with access to data on Attachment B to this Agreement. Stanford Research Organization/Stanford Researcher shall ensure the listed staff agree to comply with the terms of this Agreement.

5. Stanford Research Organization/Stanford Researcher shall not assign this Agreement or any portion thereof to a subcontractor or other third party without the prior written consent of SFUSD, and any attempted assignment without such prior written consent in violation of this Section shall automatically terminate this Agreement.

6. Stanford Research Organization/Stanford Researcher agrees that the research shall be conducted in a manner that does not permit personal identification of students, parents or staff by individuals other than representatives of the Stanford Research Organization/Stanford Researcher who have legitimate educational interests in the information.

7. Stanford Research Organization/Stanford Researcher will report only aggregate data and will not report any individual data, nor will data be reported in a manner that permits indirect identification of any individual.

8. Stanford Research Organization/Stanford Researcher will not contact the individuals included in the data sets without obtaining advance written authorization from SFUSD.

9. If the research proposal includes a survey of students, or of any other subject, then the Stanford Research Organization/Stanford Researcher shall obtain advance written approval from SFUSD's Office of Research, Planning, and Assessment ("RPA") and Stanford University's Institutional Review Board (IRB), and if such approval is granted by each of those, then Stanford Research Organization/Stanford Researcher shall also obtain prior written informed consent from the parent or legal guardian of each student participating in such survey where students are the survey subjects. If the use of surveys will be proposed, the surveys must be attached to the research application and subsequently approved by SFUSD's RPA in writing prior to use.

10. Stanford Research Organization/Stanford Researcher shall not re-disclose any individual-level data with or without identifying information to any other requesting individuals, agencies, or organizations without prior written 
authorization by SFUSD, and Stanford University shall not disclose to Stanford Research Organization or Stanford Research any personally identifiable student information (e.g., name, date of birth, address...) unless express prior written permission to do so is granted by SFUSD for a specific project only, as provided for in this Agreement.

11. Stanford Research Organization/Stanford Researcher shall use the data only for the purpose described in Section A above and according to the terms and conditions of this Agreement. These data shall not be used for personal gain or profit.

12. Stanford Research Organization/Stanford Researcher shall use reasonable and appropriate efforts to store all SFUSD data on a password-protected, secure server with encryption connected to a desktop computer in a locked-office. No data will be stored on unencrypted laptop or desktop computers or servers or unencrypted portable computing devices or media, e.g., flash drives, etc.

13. Stanford Research Organization/Stanford Researcher shall permit examination and on-site inspections by SFUSD upon reasonable advance notice for the purpose of ascertaining whether the terms of this Agreement are being met.

14. Stanford Research Organization/Stanford Researcher agrees that the confidential data shall be securely destroyed when no longer needed for the purposes for which the study was conducted. The Stanford Research Organization/Stanford Researcher shall notify the SFUSD Research, Planning, and Assessment office in writing that the data have been securely destroyed.

**I. LIABILITY**

1. Stanford Research Organization/Stanford Researcher agrees to be responsible for, and assumes all liability for, any claims, costs, damages or expenses (including reasonable attorneys' fees) that directly arise from the Stanford Research Organization/Stanford Researcher's sole intentional or negligent release of personally identifiable student, parent or staff data (collectively "Claims"). Stanford Research Organization/Stanford Researcher agrees to hold harmless SFUSD and pay any costs incurred by SFUSD in connection with any such Claim, except to the extent that the liability, claim, costs, damages, or expenses are due to the gross negligence or willful misconduct of SFUSD.

2. SFUSD agrees to be responsible for, and assumes all liability for, any claims, costs, damages or expenses (including reasonable attorneys' fees) that directly arise from SFUSD's sole intentional or negligent release of personally identifiable student, parent or staff data (collectively "Claims"). SFUSD agrees to hold harmless Stanford Research Organization/Stanford Researcher and pay any costs incurred by Stanford Research Organization/Stanford Researcher in connection with any such Claim, except to the extent that the liability, claim, costs, damages, or expenses are due to the gross negligence or willful misconduct of Stanford Research Organization/Stanford Researcher.

3. In the event of concurrent negligence of Stanford Research Organization/Stanford Researcher, its Board, officers, employees and agents, and SFUSD, its Board, officers, employees and agents, the liability for any and all claims for injuries or damages to persons and/or property shall be apportioned under the California theory of comparative negligence as presently established or as may hereafter be modified. Nothing in this Agreement shall constitute a waiver or limitation of any rights that Stanford Research Organization/Stanford Researcher may have under applicable law in the event of concurrent negligence of persons or entities other than District.

4. Stanford Research Organization/Stanford Researcher and SFUSD agree to cooperate with each other in the investigation and disposition of third-party liability claims arising out of any services provided under this Agreement. It is the intention of Stanford Research Organization/Stanford Researcher and District to fully cooperate in the disposition of all such claims. Such cooperation may include joint investigation, defense and disposition of claims of third parties arising from services performed under this Agreement. Stanford Research Organization/Stanford Researcher and District agree to promptly inform one another whenever an incident report, claim or complaint is filed or when an investigation is initiated concerning any service performed under this Agreement. A Party will not settle, or agree to settle, any claim involving the other Party without the prior written consent of the other Party.

5. The provisions of this Section shall survive the termination or expiration of this Agreement.

**J. TERMINATION**

1. This Agreement may be terminated as follows, after notification via the United States Postal Service (certified mail or registered mail) or recognized overnight delivery service (e.g., UPS, DHL or FedEx):
    a. By either party immediately in the event of a material breach of this Agreement by another party.
    b. By either party after 30 days advance written notice to the other party, for any reason or no reason.

2. The confidentiality provisions of this Agreement shall survive the expiration or termination of the Agreement. If this Agreement is terminated by either party for material breach or for any other reason with 30 days written notice, the confidential information shall be returned or securely destroyed at the direction of SFUSD within 7 days of the termination. If the Agreement terminates at the end of the term described in Section D, Stanford Research Organization/Stanford Researcher shall return or securely destroy all confidential information when it is no longer needed for the study at the direction of SFUSD. Such return or secure destruction shall occur within 7 days after it is no longer needed for the study.

3. Destruction of the confidential information shall be accomplished by utilizing an approved method of confidential destruction, including shredding, burning or certified/witnessed destruction for physical materials and verified erasure of magnetic media using approved methods of secure electronic file destruction.

**K. GENERAL UNDERSTANDING**

1. This Agreement contains the entire understanding of the parties and may only be amended in writing signed by the parties.

2. This Agreement shall be governed by and construed under the laws of the State of California, without regard to its conflict of law rules.

3. Either party's failure at any time to enforce any default or right reserved to it, or to require performance of any of the Agreement's terms, covenants, or provisions by the other party at the time designated, shall not be a waiver of any such default or right to which the party is entitled, nor shall it in any way affect the right of the party to enforce such provisions thereafter.

4. If any term or provision of this Agreement shall be found illegal or unenforceable, this Agreement shall remain in full force and effect, and such term or provision shall be deemed stricken.

5. Original copies of this Agreement shall be executed by the respective party's authorized signatory(ies). This Agreement may be executed in one or more counterparts, each of which shall be deemed an original agreement, but all of which shall be considered one instrument and shall become a binding agreement when one or more counterparts have been signed by each of the parties and delivered to the other.

6. Neither Party shall identify the other Party in any products, publicity, promotion, promotional advertising, or other promotional materials to be disseminated to the public, or use any trademark, service mark, trade name, logo, or symbol that is representative of the other Party or its entities, whether registered or not, or use the name, title, likeness, or statement of any faculty member, employee, or student, without the prior written consent of the other Party's authorized official. Any use of a Party's name shall be limited to statements of fact and shall not imply endorsement of the using Party's products or services by the other Party.

**L. PARTY SIGNATURES TO THE AGREEMENT**

**ATTACHMENT A: SPECIFIC RECORDS AND DATA ELEMENTS**

*Please specify:*

-   *study sample. Identify which school sites and which groups of students and/or staff (grade levels, program participants, etc.).*

-   *dates of data. Identify the specific time periods on which you need the data.*

-   *specific fields requested (i.e., student name, date of birth, ethnicity, gender, primary language, etc., NOT "demographic data"). Include a rationale explaining its purpose and use.  Please distinguish between variables that are critical to the analyses and variables that could be useful, if available, for adding more nuance to the findings.*

-   *The method of secure transmission of the Data and the location/address where the data is to be transferred.*

*For longitudinal, multiple-cohort analyses, you may want to include a table clearly identifying the years of data needed for each cohort.*

*If it is necessary to link administrative data with other data obtained separately by the research organization, please describe the strategy for linking the data. For example, Research Organization will provide program data for participating students, including enough identifying information to link them unambiguously to student identification numbers. The Stanford Data Manager will return these data associated with scrambled student identification numbers. Please specify which fields will be used to link records (e.g., email addresses; students' names and birthdates; etc.).*

*Data records (sample, dates), data fields, rationale*

**ATTACHMENT B: LIST OF STAFF WITH ACCESS TO SFUSD DATA**

*Please list the names and roles of all staff members affiliated with the research project who will have access to the data provided under this Agreement.*

