### Appendix A: Summary of Data Strategy Implementation (June 2020)

Below are the guidelines used to conduct implementation of the Data Strategy, as of June 2020. This summary describes the Data Strategy Implementation document which is not publicly available.

#### Data Governance {-}

- Making data searchable and managing data quality improves its usability for evidence-informed decision making.
- CCT undertook exercises to understand all data sets and metadata held by the City.
- CCT is developing a data taxonomy of the hierarchical relationships between data sets.
- CCT is developing a data dictionary of terminology and metrics. The data dictionary will standardize usage across units within CCT and improve efficiency in communication and collaboration on data projects.
- An institutionalized data governance structure ensures quality data. Empowering data collectors and generators to take ownership of the data and its quality can improve data cleaning. Human efforts can be augmented by advanced analytics that can detect anomalies and surface uncleaned data.
- CCT also provides standards for data analytics to ensure that the results provided by data analysts can be reproduced and verified.
- CCT uses open-source software, where possible, to scale analytical efforts in collaboration with service providers and academics, to reduce the time constraints of the procurement process, and to reduce the time from design to institutionalization, implementation, and outcome.

#### Data Culture {-}

- CCT's initiatives build institutional knowledge to flexibly manage data and adjust to changes both internally and externally.
- A change management plan is being rolled out to create awareness of, and desire for, working with data.

#### Data Capabilities {-}

- CCT invests in human resources to develop and manage open data architectures.
- Roll-out of training programs will build capacity with data analysts, data scientists, data engineers, data governance experts, data stewards, data custodians, user interface designers, web developers, data collectors, and other staff.
- Introducing a data literacy program will educate the organization as a whole on understanding and communicating with data.
- Data engineering efforts will build the necessary data infrastructure that will bring CCT into the big-data world, with a strong technical foundation for future analysis for decision-making.
- Guidelines on appropriate methods for data gathering and acquisition will be established.
- Strategizing survey efforts will maximize value from data collection, for example by combining household and health surveys into a single exercise.
- Open-source software can increase transparency and decrease the barrier to entry for new staff who often face a steep learning curve to understand proprietary and customized software.
- Sandbox data science and analytics environments are provided to staff, allowing allows them to fail, experiment, and learn.
- The City of Cape Town has expertise in urban monitoring and policy, but lacks the data engineering capacity to transform a data source into a useful tool for managers and policy makers. The City needs to build capacity within existing staff and employ data professionals to augment internal skills and increase data utilization. Cape Town's proximity to three major universities---the University of Cape Town, Stellenbosch University, and the University of the Western Cape---brings hundreds of skilled professionals to CCT.
