FROM rocker/r-apt:disco
RUN apt-get update
RUN apt-get install -y libcurl4-openssl-dev libxml2-dev libgdal-dev libgdal20 libudunits2-dev
RUN apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-pictures r-cran-extrafont
RUN apt-get install -y pandoc-citeproc
RUN apt-get install -y r-cran-bookdown r-cran-rprojroot 
RUN apt-get install -y r-cran-ggplot2 r-cran-ggthemes 
